tunnel: a414da5b-2dd4-4c0b-9890-6b3ff013ab18
credentials-file: /etc/cloudflared/credentials.json

ingress:
  - hostname: lockitree.com
    service: http://frontend:80
  - hostname: www.lockitree.com
    service: http://frontend:80
  - hostname: api.lockitree.com
    service: http://backend:8080
  - service: http_status:404
